### ISSUE TITLE
    from xls2xlsx import XLS2XLSX ModuleNotFoundError: No module named 'xls2xlsx

### ISSUE THREAD

**Issue by MiniFredx** [snoopyjc/xls2xlsx#13]
* xls2xlsx version: xls2xlsx==0.1.5
* Python version: Python 3.9.5
* Operating System: Windows 10

### Description

I installed via pip with: pip install xls2xlsx
The first time around I got a 

>  Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified:

So I ran it again as an admin and it worked fine.

But then when I try importing the module I get the error 

> from xls2xlsx import XLS2XLSX
> ModuleNotFoundError: No module named 'xls2xlsx'

Any idea how to fix?

**Comment by datajunkee** [comment]
An abandoned project I assume? Same issue here and was disappointed to find no responses in 9 months.  :(

**Comment by snoopyjc** [comment]
Cannot replicate this issue - please try with the latest version
