### ISSUE TITLE
Formulas with hyperlinks output empty values

### ISSUE THREAD

**Issue by ivansabik** [snoopyjc/xls2xlsx#6]
* xls2xlsx version: 0.1.5
* Python version: 3.7.0
* Operating System: OSX

### Description

I am trying to convert an XLS file containing hyperlink formulas and this is not working. Instead, it will output empty values

Original XLS
![image](https://user-images.githubusercontent.com/815440/101666469-de1a7e80-3a13-11eb-8533-5201b9c52163.png)
![image](https://user-images.githubusercontent.com/815440/101666700-276ace00-3a14-11eb-814f-a748d398063c.png)

Converted XLSX
![image](https://user-images.githubusercontent.com/815440/101666421-ce9b3580-3a13-11eb-88f1-92851d49d04f.png)

### What I Did

```
xls2xlsx /tmp/my_file.xls
```

**Comment by snoopyjc** [comment]
Hi can you upload a test case please?

-joe

**Comment by snoopyjc** [comment]
xlrd 2.0.1 has just been released - please install that and see if this issue is fixed there.  If your file is a true xls file and not an HTML xls file, then xlrd does all of the work involved in reading the file.

**Comment by ivansabik** [comment]
Thanks I will try that, I meant to upload the used file but it contains some private info I was not able to anonymize or scrub

**Comment by snoopyjc** [comment]
Ok if it’s still a problem, just try to make a similar small file that fails or only copy the bad cell(s) to a new file. 

-joe

**Comment by snoopyjc** [comment]
Sorry I can't fix this without a sample input file.  Not even sure if the input is XLS or HTML embedded in XLS.
