### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL'

### ISSUE THREAD

**Issue by opamuk** [snoopyjc/xls2xlsx#9]
* xls2xlsx version: 0.15
* Python version:3.8
* Operating System: windows 8

I tried to import xls2xlsx, but there was the error:

 File "C:\Users\mycomp\anaconda3\lib\site-packages\xls2xlsx\htmlxls2xlsx.py", line 30, in <module>
    from PIL import ImageFont

ModuleNotFoundError: No module named 'PIL'

I installed the Pillow with ; 

   conda install Pillow

but the result is the same. What should I do?

**Comment by snoopyjc** [comment]
Not sure - I’m using it per the documentation: https://pypi.org/project/Pillow/ 

Please try some of the examples documented there and maybe open an issue with that module. 

-joe

**Comment by snoopyjc** [comment]
Cannot replicate this issue
